GET http://localhost:4000

###
GET http://localhost:4000/products/4

###
POST http://localhost:4000/products
Content-Type: application/json

{
    "title":"The title"
}

###
GET http://localhost:4000/users

###
GET http://localhost:4000/users/user4